# Copyright IBM Corp. 2023
# Made available under the MIT License

name: "Login to StepZen Server"
author: "IBM"
description: |
  Log into StepZen Server

inputs:
  account:
    description: "StepZen account name"
    required: true
  adminkey:
    description: "Admin key of the StepZen account"
    required: true
  domain:
    description: "StepZen domain (defaults to stepzen.net)"
    required: true
    default: "stepzen.net"

runs:
  using: "composite"
  steps:
    # Don't assume the admin key came from a secret so mask it for safety
    - name: mask
      run: echo "::add-mask::${ inputs.adminkey }"
      shell: bash
    - name: "login"
      run: |
        stepzen login ${{ inputs.domain }} --account ${{ inputs.account }} --adminkey ${{ inputs.adminkey }}
      shell: bash
    - name: "set account environment variables"
      run: |
        apikey=$(stepzen whoami --apikey)
        echo "::add-mask::${apikey}"
        echo "STEPZEN_ACCOUNT=${{ inputs.account }}" >> $GITHUB_ENV
        echo "STEPZEN_APIKEY=${apikey}" >> $GITHUB_ENV
        echo "STEPZEN_DOMAIN=$(stepzen whoami --domain)" >> $GITHUB_ENV
      shell: bash
